spring.application.name=quemus
spring.security.user.name=admin
spotify.client-id=${SPOTIFY_CLIENT_ID: 70b096b5d4c9406da6d383a985e1cab8}
spotify.client-secret=${SPOTIFY_CLIENT_SEC:fcf6d3bcca00431f80e6ab28590dd710}
spotify.redirect-uri=${REDIRECT_URI:http://127.0.0.1:4200/api/spotify/callback}
frontend_url=${FRONTEND_URL:http://127.0.0.1:4200}
timeout.cleanup.time = ${TIMEOUT_CLEANUP:900000}

