spring.application.name=quemus
spring.security.user.name=admin
spotify.client-id=70b096b5d4c9406da6d383a985e1cab8
spotify.client-secret=fcf6d3bcca00431f80e6ab28590dd710
spotify.redirect-uri=http://127.0.0.1:4200/api/spotify/callback
frontend_url=http://127.0.0.1:4200

