spring.application.name=quemus
spring.security.user.name=admin
spring.security.user.pasword=admin123
spotify.client-id=werwer
spotify.client-secret=qwd=qwddqww
spotify.redirect-uri=http://localhost:8080/api/auth/callback
frontend_url=http://localhost:4200

